/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BattleShipGame } from "./BattleShipGame";
export * as factories from "./factories";
export { BattleShipGame__factory } from "./factories/BattleShipGame__factory";
